<!doctype html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/node_modules/bootstrap/dist/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <title>FarmaCia</title>

    <link rel="apple-touch-icon" sizes="180x180" href="assets/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="assets/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="assets/favicon-16x16.png">
    <link rel="manifest" href="assets/site.webmanifest">
    <link rel="mask-icon" href="assets/safari-pinned-tab.svg" color="#5bbad5">
    <link rel="shortcut icon" href="assets/favicon.ico">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="msapplication-config" content="assets/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">

  </head>
  <body style="min-width:372px;">
    <script src="/node_modules/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <nav id="topo" class="navbar navbar-expand-lg navbar-dark bg-primary border-bottom shadow-sm mb-3 col-12">
        <div class="container col-8 col-sm-8 col-md-8 col-lg-11 col-xl-11">        
            <button class="navbar-toggler ml-1" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!--<a class="navbar-brand" href=""><strong>FarmaVida</a>-->
            <a class="navbar-brand mr-auto" href="/">
                <img src="/assets/logo1.png" width="30" height="30" class="d-inline-block align-top" alt="">
                <strong>FarmaCia
            </a>
            <div class="navbar-collapse collapse">
                <ul class="navbar-nav flex-grow-1">
                    <li class=nav-item>
                        <a href="/medicamentos" class="nav-link text-light">Medicamentos</a>
                    </li>
                    <li class=nav-item>
                        <a href="/cosmeticos" class="nav-link text-light">Cosméticos</a>
                    </li>
                    <li class=nav-item>
                        <a href="/higiene" class="nav-link text-light">Higíene</a>
                    </li>
                    <li class=nav-item>
                        <a href="/saude" class="nav-link text-light">Saúde</a>
                    </li>
                    <li class=nav-item>
                        <a href="/infantil" class="nav-link text-light">Infantil</a>
                    </li>
                    <li class=nav-item>
                        <a href="/" class="nav-link text-light">Promoções</a>
                    </li>
                </ul>
                <div class="align-self-end">
                    <ul class="navbar-nav">
                        <li class=nav-item>
                            <a href="/cadastrarUsuario" class="nav-link text-light">Cadastrar</a>
                        </li>
                        <li class=nav-item>
                            <a href="#" class="nav-link text-light">Entrar</a>
                        </li>                      
                    </ul>
                </div>
            </div>
        </div>
        <a href="#" class="nav-link text-white mr-2">
            <svg class="bi" width="24" height="24" fill="currentColor">
                <use xlink:href="assets/bi.svg#cart3"/>
            </svg>
        </a>    
    </nav>

    <main>
      <div class="container">
        <H2>Informe seus dados, por favor</H2>
        <hr>
        <form  action="/registrarUsuario" method="post" enctype="multipart/form-data">
          <div class="row">
            <div class="col-sm-12 col-md-6">
              <fieldset class="row">
                <legend>Dados Pessoais</legend>
                <div class="mb-3 col-xl-12">
                  <label for="txtNome" class="form-label">Nome</label>
                  <input type="text"  class="form-control" id="txtNome">
                </div>
                <div class="col-md-6 col-xl-5 mb-3">
                  <label for="txtCPF"CPF class="form-label">CPF</label>
                  <span class="text-muted">(somente números)</span>
                  <input type="text" class="form-control" id="txtCPF">
                </div>
                <div class="col-md-6 col-xl-5 mb-3">
                  <label for="txtDataNascimento"CPF class="form-label" >Data de Nascimento</label>
                  <input type="date" class="form-control" id="txtDataNascimento">
                </div>
              </fieldset>
              <fieldset class="row">
                <legend>Contatos</legend>
                <div class="mb-3 col-md-8 col-xl-12">
                  <label for="txtEmail" class="form-label">E-mail</label>
                  <input type="email" class="form-control" id="txtEmail">
                </div>
                <div class="col-md-6">
                  <label for="txtTelefone" class="form-label">Telefone</label>
                  <small class="text-muted">(com DDD, somente números)</small>
                  <input type="tel" class="form-control" id="txtTelefone">                 
                </div>               
              </fieldset>
            </div>
            <div class="col-sm-12 col-md-6">
              <fieldset class="row">
                <legend>Endereço</legend>
                <div class="mb-3 col-md-6 col-lg-4">
                  <label for="txtCEP" class="form-label">CEP</label>
                  <div class="input-group">
                    <input type="text" class="form-control" id="txtCEP">
                    <span class="input-group-text p-1">
                      <svg class="bi" width="24" height="24" fill="currentColor">
                        <use xlink:href="assets/bi.svg#hourglass-split" />
                      </svg> 
                    </span>
                  </div>                 
                </div>
                <div class="mb-3 col-md-6 col-lg-8 align-self-end">
                  <textarea class="form-control text-muted bg-light" style="height:68px;">Digite o CEP para buscarmos o endereço.</textarea>
                </div>
                <div class="mb-3 col-md-4">
                  <label for="txtNumero" class="form-label">Número</label>
                  <input type="text"  class="form-control" id="txtNumero">
                </div>
                <div class="mb-3 col-md-8">
                  <label for="txtComplemento" class="form-label">Complemento</label>
                  <input type="text"  class="form-control" id="txtComplemento">
                </div>
                <div class="mb-3 col-xl-12">
                  <label for="txtReferencia" class="form-label">Referência</label>
                  <input type="text"  class="form-control" id="txtReferencia">
                </div>
              </fieldset>
              <fieldset class="row">
                <legend>Senha de Acesso</legend>
                <div class="mb-3 col-xl-12">
                  <label for="txtSenha" class="form-label">Senha</label>
                  <input type="password"  class="form-control" id="txtSenha">
                </div>
                <div class="mb-3 col-xl-12">
                  <label for="txtConfSenha" class="form-label">Confirmaçao de Senha</label>
                  <input type="password"  class="form-control" id="txtConfSenha">
                </div>
              </fieldset>
            </div>
          </div>
          <hr>
          <div class="form-check mb-3">
            <input type="checkbox" class="form-check-input" value="" id="chkPromocoes">
            <label for="chkPromocoes" class="form-check-label text-muted">Desejo receber informaçoes sobre promoções.</label>
          </div>
          <div class="mb-3">
            <a class="btn btn-light btn-outline-primary" href="/index.html">Cancelar</a>
            <input type="submit" value="Criar meu cadastro" class="btn btn-primary">
          </div>
        </form>
      </div>
    </main>

    
    <footer class="border-top text-muted bg-dark mt-2">
        <div id="rodape" class="container col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <div id="footer" class="row py-3 col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <ul id="lista" class="list-inline col-6 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                    <li>
                        <a href="" class="list-inline-item text-muted text-nowrap">Formas de Pagamento</a>
                    </li>
                    <li>
                        <a href="" class="list-inline-item text-muted">Vacinas</a>
                    </li>
                    <li>
                        <a href="" class="list-inline-item text-muted text-nowrap">Nossa História</a>
                    </li>
                    <li>
                        <a href="/cadastrarProduto" class="list-inline-item text-muted text-nowrap">Area do Administrador</a>
                    </li>
                </ul>
                <div id="redesSociais" class="text-center text-nowrap col-6 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                    <h5>Redes Sociais</h5>
                    <i class="fab fa-facebook fa-2x"></i>
                    <i class="fab fa-instagram fa-2x"></i>
                    <i class="fab fa-twitter-square fa-2x"></i>
                </div>              
            </div>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
  </body>
</html>



    
  