<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/assets/logo.png" width="100" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Cadastro realizado com sucesso</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            <a href="/" class="btn btn-primary btn-block">Fazer Login</a>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  